# Generated by Django 4.0.2 on 2023-01-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytoplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='position',
            field=models.IntegerField(),
        ),
    ]
